### ISSUE TITLE
When using media query for other elements resize event is not called for vaadin board.

### ISSUE THREAD

**Issue by rogozinds** [vaadin/vaadin-board#27]
If you have a media query and it changes the style of a component, the resize event is not fired, so vaadin board doesn't change it's appearance. The problem comes is similar to when you set width or height for board from CSS you need to call a redraw method.

**Comment by alvarezguille** [comment]
Possible solution with [requestAnimationFrame](http://caniuse.com/#search=requestAnimationFrame)

```
_onIronResize() {
  requestAnimationFrame( function() {this._recalculateFlexBasis(false)}.bind(this) ); 
}
```
