### ISSUE TITLE
Getting started uses charts even if they are not installed

### ISSUE THREAD

**Issue by Peppe** [vaadin/vaadin-board#29]
https://github.com/vaadin/board/blob/master/documentation/webcomponents-api/board-basic-use.asciidoc

Getting started documentation has these steps:
1) run bower install vaadin-board
2) ```<link rel="import" href="bower_components/vaadin-board/vaadin-board.html">```
3) use code
```
<vaadin-board>
  <vaadin-board-row>
      <vaadin-line-chart>
        <chart-title>Sales</chart-title>
        <!-- Configuration omitted -->
      </vaadin-line-chart>
      <vaadin-column-chart>
        <chart-title>Overall sales by region</chart-title>
      </vaadin-column-chart>
      <vaadin-column-chart>
        <chart-title>Services sales by region</chart-title>
      </vaadin-column-chart>
  </vaadin-board-row>
</vaadin-board>
````

Problem is that I have never installed charts so they did not render. The example was also so simple that I was not sure if board is working or is just text flowing as it should.

**Comment by web-padawan** [comment]
Fixed by https://github.com/vaadin/board/pull/26. BTW that old file should be probably removed completely.
