### ISSUE TITLE
Disable SauceLabs tests for external pull requests

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-board#50]
Currently, the TravisCI build will always fail for external PRs.

Take a look at our configuration: https://github.com/vaadin/vaadin-element-skeleton/blob/master/wct.conf.js#L16-L20

We are testing in SauceLabs only in case of `push` event, for `pull_request` we are testing only in Chrome and Firefox via Selenium.

**Comment by Artur-** [comment]
Any reason not to use https://docs.travis-ci.com/user/jwt ?

**Comment by limonte** [comment]
@Artur- we intentionally don't want external users to trigger SauceLabs test for at least 2 reasons:

- build speed - it's always good to fail and report issues early
- security - potentially they can submit a code which will test something else via our SauceLabs account

**Comment by web-padawan** [comment]
This was fixed long ago. Closing.
