### ISSUE TITLE
ES5 compiled version doesn't load in safari 10

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/vaadin-board#52]
There's a [known issue in webcomponentsjs with transpiled code and safari 10](https://github.com/webcomponents/webcomponentsjs/issues/750)

**Comment by alvarezguille** [comment]
Serving ES6 (non-transpiled) to Safari 10 prevents this issue

**Comment by web-padawan** [comment]
The related issue in the polyfills repo has been closed as stale. 
AFAIK in Flow we now serve ES6 code to Safari 10 (only IE11 gets ES5 version).

So I think this can be closed.
