### ISSUE TITLE
Dumb Question - paid component?

### ISSUE THREAD

**Issue by moderndeveloperllc** [vaadin/vaadin-board#74]
Quick question - If I'm only using this web component and not the java Vaadin Framework, is here still a license code for this?

**Comment by Peppe** [comment]
Hi! Yes. Vaadin Board is part of [Vaadin Pro](https://vaadin.com/pricing) offering under the [CVAL license](https://vaadin.com/license). The subscription includes today as web components Board and Charts and in the future even more products.

**Comment by moderndeveloperllc** [comment]
@Peppe Thanks. I understand that as a company this may seem to be necessary, but it feels very strange as this is probably the only web component library (or any frontend code for that matter) I've ever seen commercially licensed.
